## YAML Template.
---
server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: PRODUK-SERVICE
              uri: lb://PRODUK-SERVICE
              predicates:
                - Path=api/produk/**
            - id: PELANGGAN-SERVICE
              uri: lb://PELANGGAN
              predicates:
                - Path=api/pelanggan/**
            - id: ORDER
              uri: lb://ORDER
              predicates:
                - Path=api/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
